Repository sahourahh/projectIFT712, pull requests merged in 2019-12, with the labels that each got.

#4 Classifier1
  src/classifiers/classifier.py
  src/main.py
Labels: enhancement

#3 Added abstract class for classifier with hyper-parameters
  src/classifiers/parametric_classifier.py
Labels: enhancement

#14 Added verbosity option to Parametric classifiers' train method
  src/classifiers/parametric_classifier.py
Labels: enhancement

#17 Documentation fix to ParametricClassifier's train
  src/classifiers/parametric_classifier.py
Labels: documentation

#19 image processing
  src/data_manager.py
Labels: enhancement

#20 Added requirements.txt
  src/classifiers/LinearDiscriminantAnalysisClassifier.py
  src/requirements.txt
Labels: enhancement

#18 Added Linear discriminant analysis classifier
  src/classifiers/LinearDiscriminantAnalysisClassifier.py
Labels: enhancement

#21 Image processing
  src/data_manager.py
Labels: bug, enhancement

#22 Add the option to use images' data in classifier's constructor
  src/classifiers/classifier.py
  src/classifiers/parametric_classifier.py
Labels: enhancement

#16 Added SVM classifier
  src/classifiers/SvmClassifier.py
  src/classifiers/SvmRbf.py
Labels: enhancement

#15 Added AdaBoost's classifier (using DecisionTreeClassifier)
  src/classifiers/AdaBoostClassifier.py
  src/main.py
Labels: enhancement

#12 Random forest
  src/classifiers/RandomForest.py
  src/classifiers/classifier.py
  src/data_manager.py
Labels: enhancement

#11 Neurol network
  src/classifiers/NeuralNetwork.py
  src/classifiers/RandomForest.py
Labels: enhancement

#23 Added useImageData option and change tested parameters for useImageData=True
  src/classifiers/LinearDiscriminantAnalysisClassifier.py
Labels: enhancement

#24 Add report (FR)
  Rapport_Mekkid_Tahir_Vauthier.pdf
Labels: documentation

#25 Revert unwanted deletion and readability changes
  src/classifiers/classifier.py
  src/data_manager.py
Labels: bug, documentation

#26 Update report
  Rapport_Mekkid_Tahir_Vauthier.pdf
Labels: documentation

#27 Update main for fast test
  src/classifiers/AdaBoostClassifier.py
  src/classifiers/LinearDiscriminantAnalysisClassifier.py
  src/classifiers/LogisticReg.py
  src/classifiers/NeuralNetwork.py
  src/classifiers/RandomForest.py
  src/classifiers/SvmClassifier.py
  src/main.py
Labels: enhancement
